[package]
name = "database"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = { version = "0.4.38", features = ["serde"] }
futures = "0.3.30"
sqlx = { version = "0.7.4", features = ["chrono", "postgres", "runtime-tokio"] }
thiserror = "1.0.61"
